
import Banner from '../home/Banner';

const Inicio = () => {
    return (
        <section >
            <Banner>  </Banner>
            {/* <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p> */}
            {/* <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p> */}
            {/* <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos suscipit ad explicabo perspiciatis illum exercitationem laborum vitae, tempore veniam non eaque nemo odit nihil quae maiores doloribus ullam expedita laudantium molestias voluptate impedit. Quos itaque a optio architecto, eum dolorum reprehenderit beatae non sequi cumque voluptatum laborum, nesciunt ipsam vero quo. Beatae illum illo harum porro alias qui asperiores? Aperiam molestias quod sit, eligendi nisi consequuntur libero dolor, perspiciatis nostrum dolores, temporibus possimus neque a praesentium officia porro? Modi vel molestias delectus exercitationem! Non fuga molestiae natus illo, ad, eius, delectus soluta fugit repellendus consequuntur a sed molestias optio consequatur!</p>  */}
        </section>
    );
};

export default Inicio;